# Generated by Django 3.2.3 on 2021-05-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VmItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Name')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='Itemimages/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Item',
            },
        ),
    ]
