# Generated by Django 3.2.3 on 2021-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmmanager', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
